// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Decco = require("decco/src/Decco.bs.js");
var BnJs = require("bn.js");
var Js_json = require("rescript/lib/js/js_json.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var address_encode = Decco.stringToJson;

var address_decode = Decco.stringFromJson;

function bnDeccoCodex_0(bn) {
  return bn.toString();
}

function bnDeccoCodex_1(json) {
  return Belt_Option.mapWithDefault(Js_json.decodeString(json), {
              TAG: /* Error */1,
              _0: {
                path: "",
                message: "Unable to decode BN",
                value: json
              }
            }, (function (numberStr) {
                return {
                        TAG: /* Ok */0,
                        _0: new BnJs(numberStr)
                      };
              }));
}

var bnDeccoCodex = [
  bnDeccoCodex_0,
  bnDeccoCodex_1
];

var bn_encode = Curry.__1(bnDeccoCodex_0);

var bn_decode = Curry.__1(bnDeccoCodex_1);

exports.address_encode = address_encode;
exports.address_decode = address_decode;
exports.bnDeccoCodex = bnDeccoCodex;
exports.bn_encode = bn_encode;
exports.bn_decode = bn_decode;
/* bn.js Not a pure module */
