// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function $$catch(promise, callback) {
  return promise.catch(Curry.__1(callback));
}

exports.$$catch = $$catch;
/* No side effect */
